services:
  - type: web
    name: green-web-analyzer
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: ./data/database.sqlite
